services:
  circom_snarkjs:
    image: circom_snarkjs:1.0.0
    build: .
    volumes:
      - type: bind
        source: ./circom_snarkjs_workdir
        target: /circom_snarkjs_workdir
    stdin_open: true
    tty: true
